general_args:
  init_seed: 0
  local_epochs: 25 
  log_dir: "./experiments/cifar100"
  outdir: "./experiments/cifar100"
  log_file_name: '100 clients and 0.1 sample ratio'
  comm_round: 500
  n_parties: 100
  sample: 0.1
  cloud_epochs: 20
  cloud_datasize: 15000
  num_classes: 100
  cloud_alg: ""
  reset_w: false
  
device_args:
  n_worker: 32
  device: "cuda"

log_args:
  ckp_dir: "./checkpoint/"
  ckp_name: "ckp_name"

fl_args:
  optimizer: "sgd"
  lr: 0.03
  cloud_datadir: "./data/tiny-imagenet-200/train" # ./data/tiny-imagenet-200/train for TinyImagenet\n
  cloud_dataset: "tinyimagenet"
  cloud_batch_size: 64
  lr_g: 0.01

kd_args:
  kd_weight: 1.0

nas_args:
  supernet_name: "ofa_supernet_resnet50"
  tolerance: 1000
  max_try: 10000
  image_size: 32


data_args:
  dataset: 'cifar100'
  datadir: "./data"
  noise: 0
  noise_type: "level"
  partition: "noniid-labeldir"
  batch_size: 64
  beta: 0.5

