general_args:
  init_seed: 0
  local_epochs: 1 
  log_dir: "./logs_paper"
  outdir: "./logs_paper"
  log_file_name: 'cifar100_100_01_mobile'
  comm_round: 2 
  n_parties: 10
  sample: 0.2
  cloud_epochs: 1
  cloud_datasize: 1000
  
device_args:
  n_worker: 32
  device: "cuda"

log_args:
  ckp_dir: "./checkpoint/"
  ckp_name: "ckp_name"

fl_args:
  optimizer: "sgd"
  lr: 0.01
  cloud_datadir: "./data/tiny-imagenet-200/train" # ./data/tiny-imagenet-200/train for TinyImagenet\n
  cloud_dataset: "tinyimagenet"
  cloud_batch_size: 64
  lr_g: 0.01

kd_args:
  kd_weight: 1.0

nas_args:
  supernet_name: "ofa_supernet_mbv3_w12"
  tolerance: 1000
  max_try: 10000
  image_size: 32
  num_classes: 10

data_args:
  dataset: 'cifar100'
  datadir: "./data"
  noise: 0
  noise_type: "level"
  partition: "noniid-labeldir"
  batch_size: 64
  beta: 0.5

