general_args:
  ep_disctription: "not rest w for kwnwk"
  init_seed: 0
  local_epochs: 25 
  log_dir: "./experiments/cifar100/mobv2/reset"
  outdir: "./experiments/cifar100/mobv2/reset"
  log_file_name: '100 clients (14-16)'
  comm_round: 500
  n_parties: 100
  sample: 0.1
  cloud_epochs: 20
  cloud_datasize: 15000
  num_classes: 100
  cloud_alg: ""
  reset_w: true
  
device_args:
  n_worker: 32
  device: "cuda"

log_args:
  ckp_dir: "./checkpoint/"
  ckp_name: "ckp_name"

fl_args:
  optimizer: "sgd"
  lr: 0.05
  cloud_datadir: "./data/tiny-imagenet-200/train" # ./data/tiny-imagenet-200/train for TinyImagenet\n
  cloud_dataset: "tinyimagenet"
  cloud_batch_size: 64
  lr_g: 0.01

kd_args:
  kd_weight: 1.0

nas_args:
  supernet_name: "ofa_supernet_mbv3_w10"
  tolerance: 3
  max_try: 10000
  image_size: 32
  res_h: 16
  res_low: 14

data_args:
  dataset: 'cifar100'
  datadir: "./data"
  noise: 0
  noise_type: "level"
  partition: "noniid-labeldir"
  batch_size: 64
  beta: 0.5

