generual_args:
  init_seed: 0
  local_epochs: 1 
  
device_args:
  n_worker: 32
  device: "cuda"

log_args:
  log_dir: "./logs"
  log_file_name: 
  outdir: "./logs"
  ckp_dir: "./checkpoint/"
  ckp_name: "ckp_name"

fl_args:
  comm_round: 500 
  sample: 0.1
  optimizer: "sgd"
  lr: 0.01
  n_parties: 10
  cloud_epochs: 10
  cloud_datadir: "./" # ./data/tiny-imagenet-200/train for TinyImagenet\n
  cloud_datasize: 5000
  cloud_dataset: "tinyimagenet"
  cloud_batch_size: 64
  lr_g: 0.01

kd_args:
  kd_weight: 1

nas_args:
  supernet_name: "ofa_supernet_resnet50"
  tolerance: 1000
  max_try: 10000
  image_size: 32
  num_classes: 10

data_args:
  dataset: 'cifar10'
  datadir: "./data"
  noise: 0
  noise_type: "level"
  partition: "noniid-labeldir"
  batch_size: 64
  beta: 0.5

